# ========== DEV ==========
# Use the official maven/Java 8 image to create a build artifact.
# https://hub.docker.com/_/maven
FROM maven:3.8-jdk-11 as builder

# Copy local code to the container image.
WORKDIR /app
COPY pom.xml .
COPY src ./src

# Build a release artifact.
# ========== DEV ==========
RUN mvn clean package -Pdev  -DskipTests

# Use AdoptOpenJDK for base image.
# It's important to use OpenJDK 8u191 or above that has container support enabled.
# https://hub.docker.com/r/adoptopenjdk/openjdk8
# https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
FROM adoptopenjdk/openjdk11:alpine-jre

# Copy the jar to the production image from the builder stage.
# ========== test-cron-jon-mock-data ==========
COPY --from=builder /app/target/test-cron-jon-mock-data.war /test-cron-jon-mock-data.war

# Run the web service on container startup.
# ========== spring-boot-mybatis-druid ==========
CMD ["java",  "-jar", "/test-cron-jon-mock-data.war"]