FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD test-cron-jon-mock-data.jar /opt/test-cron-jon-mock-data/
EXPOSE 8080
WORKDIR /opt/test-cron-jon-mock-data/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "test-cron-jon-mock-data.jar"]
